### ISSUE TITLE
Manual install fails on apache package

### ISSUE THREAD

**Issue by phifogg** [rdynsxtrs/rn4bin#2]
Hi Stefan,
as the add-on path didn't work I tried today to follow the manual instructions. It went ok till the last command of:
```
dpkg -i --force-confold --force-overwrite apache2*.deb
Vormals nicht ausgewähltes Paket apache2 wird gewählt.
(Lese Datenbank ... 16277 Dateien und Verzeichnisse sind derzeit installiert.)
Entpacken von apache2 (aus apache2_2.2.34-0+rnx4_i386.deb) ...
Vorbereitung zum Ersetzen von apache2.2-bin 2.2.34-0+rnx1 (durch apache2.2-bin_2.2.34-0+rnx4_i386.deb) ...
Ersatz für apache2.2-bin wird entpackt ...
Vorbereitung zum Ersetzen von apache2.2-common 2.2.34-0+rnx1 (durch apache2.2-common_2.2.34-0+rnx4_i386.deb) ...
Ersatz für apache2.2-common wird entpackt ...
Vorbereitung zum Ersetzen von apache2-mpm-prefork 2.2.34-0+rnx1 (durch apache2-mpm-prefork_2.2.34-0+rnx4_i386.deb) ...
/etc/init.d/apache2: line 49: /etc/apache2/envvars: Datei oder Verzeichnis nicht gefunden
invoke-rc.d: initscript apache2, action "stop" failed.
Ersatz für apache2-mpm-prefork wird entpackt ...
Vorbereitung zum Ersetzen von apache2-utils 2.2.34-0+rnx1 (durch apache2-utils_2.2.34-0+rnx4_i386.deb) ...
Ersatz für apache2-utils wird entpackt ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von apache2.2-bin:
 apache2.2-bin hängt ab von libapr1 (>= 1.5.0); aber:
  Paket libapr1:i386 ist noch nicht konfiguriert.
 apache2.2-bin hängt ab von libaprutil1 (>= 1.5.0); aber:
  Paket libaprutil1:i386 ist noch nicht konfiguriert.
 apache2.2-bin hängt ab von libaprutil1-dbd-sqlite3 | libaprutil1-dbd-mysql | libaprutil1-dbd-odbc | libaprutil1-dbd-pgsql | libaprutil1-dbd-freetds; aber:
  Paket libaprutil1-dbd-sqlite3:i386 ist noch nicht konfiguriert.
  Paket libaprutil1-dbd-mysql ist nicht installiert.
  Paket libaprutil1-dbd-odbc ist nicht installiert.
  Paket libaprutil1-dbd-pgsql ist nicht installiert.
  Paket libaprutil1-dbd-freetds ist nicht installiert.
 apache2.2-bin hängt ab von libaprutil1-ldap; aber:
  Paket libaprutil1-ldap:i386 ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten von apache2.2-bin (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von apache2.2-common:
 apache2.2-common hängt ab von apache2.2-bin (= 2.2.34-0+rnx4); aber:
  Paket apache2.2-bin ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten von apache2.2-common (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von apache2-mpm-prefork:
 apache2-mpm-prefork hängt ab von apache2.2-common (= 2.2.34-0+rnx4); aber:
  Paket apache2.2-common ist noch nicht konfiguriert.
 apache2-mpm-prefork hängt ab von apache2.2-bin (= 2.2.34-0+rnx4); aber:
  Paket apache2.2-bin ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten von apache2-mpm-prefork (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von apache2-utils:
 apache2-utils hängt ab von libapr1 (>= 1.4.8-2~); aber:
  Paket libapr1:i386 ist noch nicht konfiguriert.
 apache2-utils hängt ab von libaprutil1 (>= 1.2.7+dfsg); aber:
  Paket libaprutil1:i386 ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten von apache2-utils (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von apache2:
 apache2 hängt ab von apache2-mpm-worker (= 2.2.34-0+rnx4) | apache2-mpm-prefork (= 2.2.34-0+rnx4) | apache2-mpm-event (= 2.2.34-0+rnx4) | apache2-mpm-itk (= 2.2.34-0+rnx4); aber:
  Paket apache2-mpm-worker ist nicht installiert.
  Paket apache2-mpm-prefork ist noch nicht konfiguriert.
  Paket apache2-mpm-event ist nicht installiert.
  Paket apache2-mpm-itk ist nicht installiert.
 apache2 hängt ab von apache2.2-common (= 2.2.34-0+rnx4); aber:
  Paket apache2.2-common ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten von apache2 (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Fehler traten auf beim Bearbeiten von:
 apache2.2-bin
 apache2.2-common
 apache2-mpm-prefork
 apache2-utils
 apache2

```

Continuing with the subsequent steps shows a bad apache config:

```

oldtown:/c/upload/debs# apachectl -t -f /etc/frontview/apache/httpd.conf
/usr/sbin/apache2: /lib/libuuid.so.1: no version information available (required by /usr/lib/i386-linux-gnu/libapr-1.so.0)
apache2: Syntax error on line 348 of /etc/frontview/apache/httpd.conf: Syntax error on line 2 of /etc/frontview/apache/addons/00_php5module.conf: Cannot load /usr/lib/apache2/modules/libphp5.so into server: /usr/lib/apache2/modules/libphp5.so: cannot open shared object file: No such file or directory
Action '-t -f /etc/frontview/apache/httpd.conf' failed.
The Apache error log may have more information.
```

It seems php5 is missing somehow. Might be a result of my trying to remove the old/bad apache package.

**Comment by phifogg** [comment]
I am also missing perl by now :/ Guess I make it worse the more I try. 
Perl was complaining about a bad version character in the package status file. Now I need to find a proper perl package to install.

**Comment by RustyDust** [comment]
> I am also missing perl by now :/ Guess I make it worse the more I try.

Looks like. Unfortunately you're not saying what you did to make Perl vanish

> Perl was complaining about a bad version character in the package status file. Now I need to find a proper perl package to install.

This has nothing to do with Perl. It's a problem with NTGR's way of mangling the database of installed packages. Actually it's just a duplicate entry iirc.
What you can try to do is a "OS reinstall" which **should** return the system and all the packages to the state of the latest firmware you installed on the ReadyNAS.

**Comment by phifogg** [comment]
I did a 'dpkg -r perl-modules' as this was the problematic package. This probably removed more than it should have.
I'll try to find how to do the OS Reinstall from command line though...

**Comment by RustyDust** [comment]
You can't do an OS reinstall from the command line. Well, you can but it requires a reboot anyway. An alternative would be to run
`apt-get install perl-modules`
but I fear NTGR has made their own version and their repos are offline by now. If the command succeeds you can try to run
`apt-get -f install`
to fix any other problems related to your packages.

**Comment by phifogg** [comment]
Partly successfull
```
oldtown:/c/upload/debs# apt-get install perl-modules
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package perl-modules is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  perl-base
E: Package perl-modules has no installation candidate
```

perl-base is installed and seems to be fine.

**Comment by RustyDust** [comment]
Well, you can give it a try using `apt-get install perl-base`

**Comment by phifogg** [comment]
I did... perl-base is installed. no errors there.

Trying OS Install now (rebooting)... Hope this just does the OS and keeps my files on the drives.

**Comment by phifogg** [comment]
Do you know if the upgrade to OS6 is an option? Sime while back I checked and it was not... by now it seems doable....

**Comment by RustyDust** [comment]
I upgraded most of my old RAIDiator 4.x systems to OS 6 years ago. However, you will have to backup your data since OS 6 will reformat all the drives.

**Comment by StephenBotzko** [comment]
Legacy 4.2.x systems can be converted if they use 64-bit architectures.  But some of the early 4.2.x systems (NVX, and first-generation Pros for example) use 32-bit architectures, and cannot be converted.

Stock memory (1 GB) doesn't seem to be enough anymore though, so you also need to ensure that you have at least 2 GB of RAM.

**Comment by RustyDust** [comment]
> Legacy 4.2.x systems can be converted if they use 64-bit architectures. 

To be precise: a 64bit CPU which is the case here.

> But some of the early 4.2.x systems (NVX, and first-generation Pros for example) 

I have a pre-first-version Pro (a beta model) and even that one's got a 64bit capable Core2-Dual CPU and was converted to OS6. The only system I know of that can't be converted is the NVX but I'm not sure whether there's also a rackmount version 
using the NVX architecture.
The OS itself is always 32 bit on RAIDiator 4.x  x86 systems.

> Stock memory (1 GB) doesn't seem to be enough anymore though, so you also need to ensure that you have at least 2 GB of RAM. 

1GB works but upgrading to 2 or even  4GB definitely makes sense.

**Comment by phifogg** [comment]
once I got it back up and operating somehow I'll check. I guess the 1 GB memory could be a culprit. It is a ReadyNas 2100 device. Not sure if/how I could upgrade memory on these.

**Comment by StephenBotzko** [comment]
>>> I have a pre-first-version Pro (a beta model) and even that one's got a 64bit capable Core2-Dual CPU and was converted to OS6.
Sorry, I mis-spoke on the first-generation Pros - obviously they can be converted

>>> I'm not sure whether there's also a rackmount version using the NVX architecture.
The 2100v1 is also 32-bit.  The 2100v2 is 64.

**Comment by RustyDust** [comment]
> once I got it back up and operating somehow I'll check. I guess the 1 GB memory could be a culprit. It is a ReadyNas 2100 device. Not sure if/how I could upgrade memory on these.

When it's up and running again, check the kernel using `uname -a`. In case it reports a 64-bit kernel your box can be upgraded to OS6.

**Comment by phifogg** [comment]
argh... it is now os reinstall'ing for about 45 minutes and not coming back up. not sure if this sounds about right...

**Comment by RustyDust** [comment]
I just started an OS reinstall on my test box. Let's see how long it takes. Specs are quite similar to your system so it should take a similar amount of time.

**Comment by RustyDust** [comment]
Ok, my test box behaves exactly the same. Problem seems to be somewhere in the boot process because the OS reinstall finishes and then the box hangs when trying to boot the newly installed OS. But to be sure I'd need to hook it up to a monitor which means disassembling the whole thing first to connect the VGA cable. I guess I'll first try to use a recovery USB stick.

**Comment by phifogg** [comment]
damn... somehow good to hear you have the same issue but not good in terms of getting back only. I would love to avoid the factory reset though.
Need to check if mine has a vga port or not ... could get it out of the rack to test...

**Comment by RustyDust** [comment]
Even using USB recovery didn't bring back my box. Next stop: Tech support mode.

**Comment by phifogg** [comment]
Same here. I don't know enough about tech support mode though. And as mine does not have a vga port i am pretty lost i guess.

**Comment by RustyDust** [comment]
I'm in on my box using tech support mode. I think I found the source of the problem - now trying to find a way to solve it that doesn't require a factory reset. Stay tuned.

**Comment by RustyDust** [comment]
Ha! I did it. With some pretty ugly surgery I was able to revive my ReadyNAS using tech support mode. If you want me to give it a try on your ReadyNAS as well, drop me an email.

**Comment by phifogg** [comment]
I did drop you an email. Happy to do what I have to :D I am quite fond with linux usually.

**Comment by RustyDust** [comment]
I just released a new version. Should now work with the [manual procedure via SSH](https://github.com/rdynsxtrs/rn4bin/tree/main/apache2/x86#using-the-command-line-via-ssh) as outlined in the [README](https://github.com/rdynsxtrs/rn4bin/tree/main/apache2/x86#using-the-command-line-via-ssh)
