### ISSUE TITLE
ReadyNas 4.2.24 won't boot

### ISSUE THREAD

**Issue by jjcf89** [rdynsxtrs/rn4bin#3]
I didn't notice the big warning not to use this updated.

I updated RAIDiator from 4.2.24 to 4.2.31. And installed this update at the same time.

If I boot into tech support mode using the following instructions:
https://kb.netgear.com/22891/How-do-I-access-the-boot-menu-on-my-ReadyNAS-104-204-214-or-314
http://clusterfrak.com/kb/appliance_kb/readynas_recovery/

I get an error about invalid ABI when I try to chroot to /sysroot

```
# chroot /sysroot/
/bin/sh: error while loading shared libraries: /lib/i386-linux-gnu/i686/cmov/libc.so.6: ELF file OS ABI invalid
```

**Comment by jjcf89** [comment]
Would this file have been part of the apache upgrade or is this caused by the upgrade to 4.2.31?

**Comment by RustyDust** [comment]
You can fix the boot-problem by issuing the following command when in "tech support mode" and having mounted the boot volume to `/sysroot`: 

`rm -rf /sysroot/lib/i386-linux-gnu/i686` 

Note that this will allow the NAS to boot but it won't fix the broken web interface.

**Comment by jjcf89** [comment]
Gotcha, should I try to downgrade the deb packages?

**Comment by RustyDust** [comment]
If you know what you're doing you can try that. That said, it may be safer to do an OS reinstall since some of the packages in the OS were modified by NTGR but their repo has been taken down a few years ago.

**Comment by jjcf89** [comment]
I'm familiar with debian based systems though not readynas specifically.

Any idea if there are any files on the /sysroot partition that I should grab to make the restore easier, before doing an os reinstall?

**Comment by jjcf89** [comment]
Though looks like the os reinstall won't wipe most settings so that's good.

> OS reinstall. 
> Reinstalls the firmware from the internal flash to the disks. The OS reinstall boot mode can be useful when the system crashes and corrupts some configuration files. OS reinstall boot mode also resets some settings on your storage system, such as Internet protocol settings and the administrator password, to defaults.

**Comment by RustyDust** [comment]
OS reinstall is as non.destructive as it can be. What it does, however, is to reset your admin password to "netgear1". Other than that your data isn't touched. Unfortunately that's also true for installed but broken libraries and binaries. If those aren't overwritten by older version they'll stay broken.
I think I found the problem with the Apache2.bin but to make sure it would be nice if you could post the output of

`cat /proc/cpuinfo`

from your NAS.

**Comment by jjcf89** [comment]
```
sh-3.1# cat /proc/cpuinfo | head -20
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 28
model name      : Intel(R) Atom(TM) CPU D510   @ 1.66GHz
stepping        : 10
cpu MHz         : 1662.127
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dts
bogomips        : 3324.25
...
```

**Comment by RustyDust** [comment]
Thanks, it's what I thought. It's only failing on Atom CPUs.

**Comment by jjcf89** [comment]
Not sure if this helps, apache is built for a different GNU/Linux than other binaries.

```
sh-3.1# file /usr/sbin/apache2
/usr/sbin/apache2: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.4.1, stripped
sh-3.1# file /lib/libc.so.6
/lib/libc.so.6: symbolic link to `libc-2.7.so'
sh-3.1# file /lib/libc-2.7.so
/lib/libc-2.7.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.8, stripped

sh-3.1# file lib/i386-linux-gnu/libc-2.19.so
lib/i386-linux-gnu/libc-2.19.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped
sh-3.1# file lib/i386-linux-gnu/i686.bak/cmov/libc-2.19.so
lib/i386-linux-gnu/i686.bak/cmov/libc-2.19.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped

sh-3.1# ldd usr/sbin/apache2
usr/sbin/apache2: /lib/libc.so.6: version `GLIBC_2.15' not found (required by /usr/lib/libapr-1.so.0)
        linux-gate.so.1 =>  (0xffffe000)
        libssl.so.0.9.8 => /usr/lib/i686/cmov/libssl.so.0.9.8 (0xf7745000)
        libcrypto.so.0.9.8 => /usr/lib/i686/cmov/libcrypto.so.0.9.8 (0xf75ea000)
        libm.so.6 => /lib/libm.so.6 (0xf75c3000)
        libpcre.so.3 => /lib/i386-linux-gnu/libpcre.so.3 (0xf754c000)
        libaprutil-1.so.0 => /usr/lib/libaprutil-1.so.0 (0xf7527000)
        libldap_r.so.2 => /usr/lib/libldap_r.so.2 (0xf74f2000)
        liblber.so.2 => /usr/lib/liblber.so.2 (0xf74e6000)
        libdb-4.4.so => /usr/lib/libdb-4.4.so (0xf73eb000)
        libpq.so.4 => /usr/lib/libpq.so.4 (0xf73cd000)
        libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0xf733e000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0xf731e000)
        libapr-1.so.0 => /usr/lib/libapr-1.so.0 (0xf72ec000)
        libuuid.so.1 => /lib/libuuid.so.1 (0xf72e8000)
        librt.so.1 => /lib/librt.so.1 (0xf72df000)
        libcrypt.so.1 => /lib/libcrypt.so.1 (0xf72ac000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf7294000)
        libdl.so.2 => /lib/libdl.so.2 (0xf7290000)
        libc.so.6 => /lib/libc.so.6 (0xf7152000)
        libz.so.1 => /usr/lib/libz.so.1 (0xf713d000)
        /lib/ld-linux.so.2 (0xf779b000)
        libresolv.so.2 => /lib/libresolv.so.2 (0xf7129000)
        libsasl2.so.2 => /usr/lib/libsasl2.so.2 (0xf7112000)
        libgnutls.so.13 => /usr/lib/libgnutls.so.13 (0xf70a4000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0xf7010000)
        libcom_err.so.2 => /lib/libcom_err.so.2 (0xf700d000)
        libtasn1.so.3 => /usr/lib/libtasn1.so.3 (0xf6ffc000)
        libgcrypt.so.11 => /usr/lib/libgcrypt.so.11 (0xf6f85000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0xf6f81000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0xf6f5d000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0xf6f55000)
        libkeyutils.so.1 => /lib/libkeyutils.so.1 (0xf6f51000)

```

**Comment by RustyDust** [comment]
I'm currently rebuilding the whole chain, including the fix for i686 CPUs.

**Comment by jjcf89** [comment]
> OS reinstall is as non.destructive as it can be. What it does, however, is to reset your admin password to "netgear1". Other than that your data isn't touched. Unfortunately that's also true for installed but broken libraries and binaries. If those aren't overwritten by older version they'll stay broken

Do we know if the reinstall actually fixes this?  Should I just wait for your rebuild?

**Comment by phifogg** [comment]
Reinstall did not fix it for me. So I am also waiting for RustyDust's new packages.

**Comment by jjcf89** [comment]
Same, reinstall didn't help.  NAS hangs during boot. Even with the removed /sysroot/lib/i386-linux-gnu/i686

**Comment by jjcf89** [comment]
Note after the os reinstall.  Went back into tech support mode, and chrooting into /sysroot is back to broken.  Error doesn't give me much to go off other than things are in a bad place if malloc is throwing errors.

```
# chroot /sysroot

malloc: unknown:0: assertion botched
free: called with already freed block argument
last command: (null)
Aborting...Aborted
```

**Comment by RustyDust** [comment]
> Note after the os reinstall. Went back into tech support mode, and chrooting into /sysroot is back to broken. 

You can try to

`rm -rf /sysroot/lib/i386-linux-gnu`

as well.

**Comment by jjcf89** [comment]
That did let me get back into chroot

**Comment by RustyDust** [comment]
It should also make the ReadyNAS boot without the web interface but with the general sharing services enabled and active.

**Comment by jjcf89** [comment]
Won't let me reboot it remotely.  The /dev directory isn't mounted correctly in the chroot..  

```
# mount
rootfs on / type rootfs (rw)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
tmpfs on /dev type tmpfs (rw,relatime,size=10240k,mode=755)
devpts on /dev/pts type devpts (rw,relatime,mode=600)
/dev/md0 on /sysroot type ext3 (rw,relatime,errors=continue,barrier=0,data=ordered)
/proc on /sysroot/proc type proc (rw,relatime)
tmpfs on /sysroot/dev type tmpfs (rw,relatime,size=10240k,mode=755)
# ls /dev
0:0:0:0             fuse                md0                 sda                 sg0                 tty16               tty29               tty41               tty54               ttyS0
...
# ls /sysroot/dev
0:0:0:0             fuse                md0                 sda                 sg0                 tty16               tty29               tty41               tty54               ttyS0
...
# chroot /sysroot
sh-3.1# mount
sh-3.1# ls /dev
0:0:0:0        console          device-mapper  loop1  loop7   md2                 null    sda   sdb2  sdd   tgt    tty12  tty18  tty23  tty29  tty34  tty4   tty45  tty50  tty56  tty61  ttyS0    vcs
1:0:0:0        cpu0             full           loop2  mapper  mem                 port    sda1  sdb3  sdd1  tty    tty13  tty19  tty24  tty3   tty35  tty40  tty46  tty51  tty57  tty62  ttyS1    vcs1
4:0:0:0        cpu1             fuse           loop3  mcelog  mpt2ctl             ptmx    sda2  sdc   sg0   tty0   tty14  tty2   tty25  tty30  tty36  tty41  tty47  tty52  tty58  tty63  ttyS2    vcsa
6:0:0:0        cpu2             i2c-0          loop4  md      mptctl              pts     sda3  sdc1  sg1   tty1   tty15  tty20  tty26  tty31  tty37  tty42  tty48  tty53  tty59  tty7   ttyS3    vcsa1
btrfs-control  cpu3             kmsg           loop5  md0     network_latency     random  sdb   sdc2  sg2   tty10  tty16  tty21  tty27  tty32  tty38  tty43  tty49  tty54  tty6   tty8   tun      vpd
c              cpu_dma_latency  loop0          loop6  md1     network_throughput  rtc0    sdb1  sdc3  sg3   tty11  tty17  tty22  tty28  tty33  tty39  tty44  tty5   tty55  tty60  tty9   urandom  zero
sh-3.1# reboot
shutdown: /dev/initctl: No such file or directory
init: /dev/initctl: No such file or directory
sh-3.1#
```

**Comment by RustyDust** [comment]
Just turn it off and on again. Reboot / poweroff won't work in tech support mode.

**Comment by RustyDust** [comment]
I just released a new version. Downside for you: you need to use the [manual procedure via SSH](https://github.com/rdynsxtrs/rn4bin/tree/main/apache2/x86#using-the-command-line-via-ssh) as outlined in the [README](https://github.com/rdynsxtrs/rn4bin/tree/main/apache2/x86#using-the-command-line-via-ssh)

**Comment by jjcf89** [comment]
Okay, can I do this from the tech support mode?

**Comment by jjcf89** [comment]
> Okay, can I do this from the tech support mode?

nvm, i got it to boot in normal mode

**Comment by jjcf89** [comment]
[server_apache_fix.log](https://github.com/rdynsxtrs/rn4bin/files/8257499/server_apache_fix.log)

Was able to manually install deb packages after figuring out git lfs xD.  The server is back up and working. woo

**Comment by jjcf89** [comment]
Thanks for your help
