### ISSUE TITLE
RAIDiator 4.1.16 [1.00a043]   Nas Ready Duo V1

### ISSUE THREAD

**Issue by Puy-Robin** [rdynsxtrs/rn4bin#7]
Can this be made to work with RAIDiator 4.1.16 [1.00a043]   Nas Ready Duo V1 ?

**Comment by Puy-Robin** [comment]
I have tried Apache2_2.2.34-x86-0.2.0.bin
Update file is not valid for this architecture.

**Comment by RustyDust** [comment]
Sorry, this won’t work and unfortunately it can’t be made to work since the base OS and the tool chains are way out of date on the SPARC platform. That said I’d be willing to part with my development environment for that platform (a rackmount UltraSPARC II) for the cost of shipment.
