### ISSUE TITLE
Invalid image error 

### ISSUE THREAD

**Issue by grtessman** [rdynsxtrs/rn4bin#8]
Hi,

I am using ReadyNAS 600-TL (Radiator 4.1.16) and also a ReadyNAS NV+ (Radiator 4.1.16) and both of these are reporting back "Invalid image" error when trying to upload add-on image: Apache2_2.2.34-x86-0.2.0.bin

Wondering if you may have any ideas?

![image](https://user-images.githubusercontent.com/1221186/175436789-91ac67a8-c62f-493e-8ed5-baa8370811b1.png)

![image](https://user-images.githubusercontent.com/1221186/175436939-ded56131-8898-4d4e-a3a0-32aff4373885.png)

**Comment by grtessman** [comment]
Maybe these are both Sparc based systems?  I don't even remember how to check anymore...

**Comment by RustyDust** [comment]
You guessed correctly: these are SPARC based systems. If unsure about the hardware architecture of your ReadyNAS there‘s an easy rule of thumb:

* RAIDiator 4.1.x -> SPARC
* RAIDiator 4.2.x -> x86
* RAIDiator 5.x -> ARM

For the ReadyNAS OS 6 products the distinction can be made by model number:

* RN1xx / RN2xx -> ARM
* everything else -> x86_64

So, sadly, the files in this repo won’t work for you.
